# Site settings
title: Pumpkinz
email: pumpkinz.dev@gmail.com
description: >
  Pumpkinz | Joint coalition of Software Engineers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.pumpkinz.io" # the base hostname & protocol for your site
github_username:  pumpkinz
image: "/images/parallax.jpg"

# Theme settings
theme_color: "#EF6C00"

# Touch icon settings
chrome_touch_icon: "/images/touch/chrome-touch-icon-192x192.png"
apple_touch_icon: "/images/touch/apple-touch-icon.png"
ms_tile_image: "/images/touch/ms-touch-icon-144x144-precomposed.png"

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: :compressed
